"""initial schema

Revision ID: 1576a61b6fbe
Revises: 
Create Date: 2026-06-30 18:34:27.469708
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1576a61b6fbe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pseudonym', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_pseudonym'), 'patients', ['pseudonym'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('medecin', 'physicien', 'manipulateur', 'admin', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('calibration_factors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('isotope', sa.Enum('Tc-99m', 'I-123', 'I-131', 'In-111', 'Lu-177', name='isotope'), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_identities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('identity_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('studies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('exam_type', sa.Enum('bone', 'myocardial_spect', 'mibg', 'octreotide', 'parathyroid', 'lung_vq', name='exam_type'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'anonymizing', 'separating', 'converting', 'segmenting', 'registering', 'quantifying', 'dosimetry', 'analyzing', 'generating_report', 'ready', 'error', name='study_status'), nullable=False),
    sa.Column('isotope', sa.Enum('Tc-99m', 'I-123', 'I-131', 'In-111', 'Lu-177', name='isotope'), nullable=True),
    sa.Column('radiopharmaceutical', sa.String(length=255), nullable=True),
    sa.Column('injected_activity_mbq', sa.Numeric(), nullable=True),
    sa.Column('injection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acquisition_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('radiopharmaceutical', sa.String(length=255), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=True),
    sa.Column('administered_activity_mbq', sa.Numeric(), nullable=True),
    sa.Column('administered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('study_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=45).with_variant(postgresql.INET(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dosimetry_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=True),
    sa.Column('treatment_id', sa.Uuid(), nullable=True),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('absorbed_dose_gy', sa.Numeric(), nullable=False),
    sa.Column('uncertainty_gy', sa.Numeric(), nullable=True),
    sa.Column('tia', sa.Numeric(), nullable=True),
    sa.Column('method', sa.Enum('multi_timepoint', 'single_timepoint', name='dosimetry_method'), nullable=False),
    sa.Column('engine', sa.String(length=32), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('score_type', sa.Enum('krenning', 'curie', 'siopen', 'pioped', 'bsi', 'bsi_proxy', 'lvef', 'sss', 'srs', 'sds', 'tid', name='score_type'), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lesions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('anatomical_ref', sa.String(length=255), nullable=True),
    sa.Column('intensity', sa.Numeric(), nullable=True),
    sa.Column('ratio', sa.Numeric(), nullable=True),
    sa.Column('size_mm', sa.Numeric(), nullable=True),
    sa.Column('is_physiological', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organ_measurements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('organ_name', sa.String(length=255), nullable=False),
    sa.Column('snomed_code', sa.String(length=64), nullable=True),
    sa.Column('volume_ml', sa.Numeric(), nullable=True),
    sa.Column('mean_intensity', sa.Numeric(), nullable=True),
    sa.Column('activity_mbq', sa.Numeric(), nullable=True),
    sa.Column('concentration_mbq_ml', sa.Numeric(), nullable=True),
    sa.Column('pct_injected_activity', sa.Numeric(), nullable=True),
    sa.Column('segmentation_corrected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'edited', 'validated', name='report_status'), nullable=False),
    sa.Column('validated_by', sa.Uuid(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_id')
    )
    op.create_table('study_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('study_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('ct', 'spect', name='series_kind'), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('anonymized', sa.Boolean(), nullable=False),
    sa.Column('time_point', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ai_draft', 'edited', 'validated', name='report_version_kind'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('ai_model_version', sa.String(length=128), nullable=True),
    sa.Column('author', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_versions')
    op.drop_table('study_series')
    op.drop_table('reports')
    op.drop_table('organ_measurements')
    op.drop_table('lesions')
    op.drop_table('exam_scores')
    op.drop_table('dosimetry_results')
    op.drop_table('audit_log')
    op.drop_table('treatments')
    op.drop_table('studies')
    op.drop_table('patient_identities')
    op.drop_table('calibration_factors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_pseudonym'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('devices')
    # ### end Alembic commands ###
