"""patient linkage hash

Revision ID: 89bc0fb1b73c
Revises: e4ce5b593e78
Create Date: 2026-06-30 20:44:10.373599
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89bc0fb1b73c"
down_revision: str | None = "e4ce5b593e78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("patients", sa.Column("linkage_hash", sa.String(length=64), nullable=True))
    op.create_index(op.f("ix_patients_linkage_hash"), "patients", ["linkage_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patients_linkage_hash"), table_name="patients")
    op.drop_column("patients", "linkage_hash")
    # ### end Alembic commands ###
